# -*- coding: utf-8 -*-
"""CodeAlpha_Unemployment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-ld69jIpqq8pMOEHmDvvNmzfJC3rGoR
"""

# ==========================================================
# TASK 2: UNEMPLOYMENT ANALYSIS WITH TWO DATASETS
# CodeAlpha Internship
# ==========================================================

# -----------------------------
# 1. Import Libraries
# -----------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files # Added for file upload

# -----------------------------
# 2. Load BOTH Datasets
# -----------------------------
# Prompt user to upload 'Unemployment in India.csv'
print("Please upload 'Unemployment in India.csv':")
uploaded_india = files.upload()

# Assuming only one file is uploaded for df1
df1 = pd.DataFrame()
if uploaded_india:
    filename_india = next(iter(uploaded_india))
    df1 = pd.read_csv(filename_india)
    print(f"Successfully loaded '{filename_india}'")
else:
    print("No file uploaded for 'Unemployment in India.csv'. Analysis may be incomplete.")

# Prompt user to upload 'Unemployment Rate up to 2020.csv'
print("\nPlease upload 'Unemployment Rate up to 2020.csv':")
uploaded_rate = files.upload()

# Assuming only one file is uploaded for df2
df2 = pd.DataFrame()
if uploaded_rate:
    filename_rate = next(iter(uploaded_rate))
    df2 = pd.read_csv(filename_rate)
    print(f"Successfully loaded '{filename_rate}'")
else:
    print("No file uploaded for 'Unemployment Rate up to 2020.csv'. Analysis may be incomplete.")

# Check if dataframes are loaded before proceeding
if not df1.empty and not df2.empty:
    print("Dataset 1 Shape:", df1.shape)
    print("Dataset 2 Shape:", df2.shape)

    # -----------------------------
    # 3. Clean Dataset 1
    # -----------------------------
    df1.columns = df1.columns.str.strip()
    df1['Date'] = pd.to_datetime(df1['Date'], dayfirst=True)
    df1 = df1.dropna()

    # -----------------------------
    # 4. Clean Dataset 2
    # -----------------------------
    df2.columns = df2.columns.str.strip()
    df2['Date'] = pd.to_datetime(df2['Date'], dayfirst=True)
    df2 = df2.dropna()

    # -----------------------------
    # 5. Merge the Datasets
    # -----------------------------
    df = pd.concat([df1, df2], ignore_index=True)

    print("\nMerged Dataset Shape:", df.shape)

    # -----------------------------
    # 6. Basic Data Analysis
    # -----------------------------
    print("\nDataset Info:")
    print(df.info())

    print("\nStatistical Summary:")
    print(df.describe())

    # -----------------------------
    # 7. Unemployment Rate Over Time
    # -----------------------------
    plt.figure(figsize=(10,5))
    plt.plot(df['Date'], df['Estimated Unemployment Rate (%)'])
    plt.xlabel("Date")
    plt.ylabel("Unemployment Rate (%)")
    plt.title("Unemployment Rate in India Over Time")
    plt.grid()
    plt.show()

    # -----------------------------
    # 8. Region-wise Unemployment
    # -----------------------------
    plt.figure(figsize=(12,6))
    sns.barplot(x='Region', y='Estimated Unemployment Rate (%)', data=df)
    plt.xticks(rotation=90)
    plt.title("Region-wise Unemployment Rate")
    plt.show()

    # -----------------------------
    # 9. Covid-19 Impact Analysis
    # -----------------------------
    before_covid = df[df['Date'] < '2020-03-01']
    after_covid = df[df['Date'] >= '2020-03-01']

    plt.figure(figsize=(10,5))
    plt.plot(before_covid['Date'], before_covid['Estimated Unemployment Rate (%)'], label='Before Covid')
    plt.plot(after_covid['Date'], after_covid['Estimated Unemployment Rate (%)'], label='After Covid')
    plt.xlabel("Date")
    plt.ylabel("Unemployment Rate (%)")
    plt.title("Covid-19 Impact on Unemployment")
    plt.legend()
    plt.grid()
    plt.show()

    # -----------------------------
    # 10. Seasonal Trend
    # -----------------------------
    df['Month'] = df['Date'].dt.month

    plt.figure(figsize=(8,5))
    sns.boxplot(x='Month', y='Estimated Unemployment Rate (%)', data=df)
    plt.title("Seasonal Unemployment Trend")
    plt.show()

    # -----------------------------
    # 11. Correlation Heatmap
    # -----------------------------
    plt.figure(figsize=(6,4))
    sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
    plt.title("Correlation Matrix")
    plt.show()

    # -----------------------------
    # 12. Key Insights
    # -----------------------------
    print("\nKEY INSIGHTS:")
    print("1. Unemployment rate peaked during Covid-19 lockdown period.")
    print("2. Certain regions consistently report higher unemployment.")
    print("3. Seasonal variations affect unemployment rates.")
    print("4. Combining datasets gives a broader trend analysis.")

    print("\nTASK 2 COMPLETED SUCCESSFULLY")
else:
    print("\nCannot proceed with analysis: One or both datasets failed to load.")