# -*- coding: utf-8 -*-
"""codealpha_car_price_prediction_with_machine_learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrMo3hNj0e9-RGADarrdv-Se0EqTrdW-
"""

# ==================================================
# TASK 3 — CAR PRICE PREDICTION WITH MACHINE LEARNING
# ==================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


# ===============================
# 1. LOAD THE DATASET
# ===============================
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/car data.csv")   # <<< replace with your file name

print(df.head())
print(df.info())


# ===============================
# 2. CLEANING + FEATURE ENGINEERING
# ===============================

# Remove duplicates
df = df.drop_duplicates()

# Fill missing values
df = df.fillna(df.median(numeric_only=True))

# Feature Engineering Examples:
if 'year' in df.columns:
    df['car_age'] = 2025 - df['year']

# Optional: Convert km or mileage to numeric
for col in df.columns:
    if "km" in col.lower() or "mileage" in col.lower():
        df[col] = df[col].astype(str).str.replace(",", "").str.extract("(\d+\.?\d*)").astype(float)


# ===============================
# 3. SELECT FEATURES & TARGET
# ===============================

y = None
for col in df.columns:
    if "price" in col.lower():
        y = df[col]
        break

if y is None:
    raise ValueError("Price column not found!")

X = df.drop(columns=[col for col in df.columns if "price" in col.lower()])


# ===============================
# 4. SPLIT NUM / CAT FEATURES
# ===============================

num_features = X.select_dtypes(include=['int64', 'float64']).columns
cat_features = X.select_dtypes(include=['object']).columns

print("Numerical Features:", num_features)
print("Categorical Features:", cat_features)


# ===============================
# 5. PREPROCESSING PIPELINE
# ===============================

preprocess = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_features),
        ('cat', OneHotEncoder(handle_unknown="ignore"), cat_features)
    ]
)


# ===============================
# 6. MODELS
# ===============================

models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=200, random_state=42)
}

results = {}

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

for name, model in models.items():
    pipe = Pipeline(steps=[('prep', preprocess),
                          ('model', model)])

    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)

    # Calculate RMSE by taking the square root of MSE
    rmse = np.sqrt(mean_squared_error(y_test, pred))
    r2 = r2_score(y_test, pred)

    results[name] = {"RMSE": rmse, "R2": r2}

    print(f"\n===== {name} =====")
    print("RMSE:", rmse)
    print("R2 Score:", r2)


# ===============================
# 7. VISUALIZATION — ACTUAL VS PREDICTED (RF)
# ===============================

best_model = RandomForestRegressor(n_estimators=200, random_state=42)
pipe = Pipeline(steps=[("prep", preprocess), ("model", best_model)])
pipe.fit(X_train, y_train)
pred = pipe.predict(X_test)

plt.figure(figsize=(8,5))
plt.scatter(y_test, pred, color='purple')
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted Car Price")
plt.grid()
plt.show()

print("\nTask 3 Completed Successfully!")