# -*- coding: utf-8 -*-
"""CodeAlpha_Iris_Flower_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lEG4TCoxEVEovGZT9Gqi0YqB58TxN94
"""

#  IRIS CLASSIFICATION

import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Load dataset
df = pd.read_csv("Iris.csv")

# Features and target
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Encode target labels
le = LabelEncoder()
y = le.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# SVM (best for Iris)
svc = SVC()

# Hyperparameter tuning
params = {
    "C": [0.1, 1, 10, 50, 100],
    "gamma": [0.001, 0.01, 0.1, 1],
    "kernel": ["rbf"]
}

grid = GridSearchCV(svc, params, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)

best_model = grid.best_estimator_
print("Best Parameters:", grid.best_params_)

# Predictions
pred = best_model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, pred)
print("FINAL MODEL ACCURACY:", accuracy)

# Classification report
print("\nClassification Report:")
print(classification_report(y_test, pred, target_names=le.classes_))

# Confusion Matrix
cm = confusion_matrix(y_test, pred)
sns.heatmap(cm, annot=True, cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
plt.title("Confusion Matrix - Random Forest")
plt.show()